name: Beta Build and Release
on:
  workflow_dispatch:
    inputs:
      app_branch:
        description: 'Branch for Touch-N-Stars app (z.B. main, develop, feature/xyz)'
        required: true
        default: 'main'
        type: string
permissions:
  contents: write
env:
  PLUGIN_NAME: "Touch-N-Stars"
  PLUGIN_DLL_NAME: "TouchNStars"
jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare folders
        run: |
          mkdir packages
          mkdir packages/${{ env.PLUGIN_NAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Pull and build external repository
        run: |
          git clone --branch ${{ inputs.app_branch }} https://github.com/JohannesWorks/Touch-N-Stars.git external_repo
          cd external_repo
          npm install
          npm run build
          cd ..
          mv external_repo/dist app
      - name: Get Assembly Version
        id: get_version
        run: |
          $version = (Select-String -Path "Touch-N-Stars/Properties/AssemblyInfo.cs" -Pattern 'AssemblyVersion\("([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"\)').Matches.Groups[1].Value
          echo "version=$version" >> $env:GITHUB_OUTPUT
      - name: Build .NET Assemblies
        run: |
          dotnet restore
          dotnet build ${{ env.PLUGIN_NAME }}.sln -c Release -p:PostBuildEvent= -p:Version=${{ steps.get_version.outputs.version }}
      - name: Prepare package
        run: |
          Copy-Item "Touch-N-Stars/bin/Release/net8.0-windows/${{ env.PLUGIN_DLL_NAME }}.dll" "packages/${{ env.PLUGIN_NAME }}/${{ env.PLUGIN_DLL_NAME }}.dll" -Force
          Copy-Item "Touch-N-Stars/bin/Release/net8.0-windows/${{ env.PLUGIN_DLL_NAME }}.pdb" "packages/${{ env.PLUGIN_NAME }}/${{ env.PLUGIN_DLL_NAME }}.pdb" -Force
          Copy-Item "Touch-N-Stars/extra-libs/*.dll" "packages/${{ env.PLUGIN_NAME }}/" -Force
  
      - name: Add app folder to package
        run: |
            $targetPath = "packages/${{ env.PLUGIN_NAME }}/app"
            if (Test-Path $targetPath) {
              Remove-Item -Path $targetPath -Recurse -Force
            }
            New-Item -ItemType Directory -Path $targetPath -Force
            Copy-Item -Recurse -Force app/* $targetPath
  
      - name: Create Plugin archives and manifests
        run: |
            curl https://raw.githubusercontent.com/isbeorn/nina.plugin.manifests/refs/heads/main/tools/CreateNET7Manifest.ps1 >> CreateNET7Manifest.ps1
            pwsh CreateNET7Manifest.ps1 -file "packages/${{ env.PLUGIN_NAME }}/${{ env.PLUGIN_DLL_NAME }}.dll" -installerUrl "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/${{ env.PLUGIN_DLL_NAME }}.zip" -createArchive -includeAll
            Get-ChildItem -Recurse *.zip
            Rename-Item -Path "manifest.json" -NewName "manifest.json"
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            TouchNStars.zip
            manifest.json